version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana72
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch1:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=es-cluster
      # 在同一个网络里面可以通过container_name进行通信
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data1:/usr/share/elasticsearch/data
    networks:
      - esnet
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/usr/share/elasticsearch/data
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data3:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  data1:
  data2:
  data3:

networks:
  esnet:
