version: '3.7'
services:
  # elasticsearch集群
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana72
    # environment支持字典和数组的形式进行配置
    # 字典形式 key=value
    # 数组形式 -key=value
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200
      XPACK_GRAPH_ENABLED: true
      TIMELION_ENABLED: true
      XPACK_MONITORING_COLLECTION_ENABLED: true
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch1:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  # elasticsearch集群
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=es-cluster
      # 在同一个网络里面可以通过container_name进行通信
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # 主机端口映射，可以通过宿主机访问容器里面的信息，由于不需要对外暴露，所以可以注释
    # ports:
    #   - 9200:9200
    #   - 9300:9300
    volumes:
      - data1:/usr/share/elasticsearch/data
    # 
    networks:
      - esnet
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/usr/share/elasticsearch/data
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data3:/usr/share/elasticsearch/data
    networks:
      - esnet

#配置数据卷
volumes:
  data1:
    # 指定volume的名称，不指定默认是{project_name}_data1，project_name是文件夹的名字
    name: data1
  data2:
    name: data2
  data3:
    name: data3

#创建esnet的网络
networks:
  esnet: